###
get  https://nrs-backend.herokuapp.com/categories
content-Type: application/json

{

}


###
put  https://nrs-backend.herokuapp.com/categories/461
content-Type: application/json

{
    "naziv":"Toaletska vodica",
    "nadkategorija":1

}

###
post  https://nrs-backend.herokuapp.com/categories
content-Type: application/json

{
    "naziv":"Parfemi",
    "nadkategorija":null

}

###
post  https://nrs-backend.herokuapp.com/people
content-Type: application/json

{
    "lokacija":"kuca",
    "ime":"kerim",
    "prezime":"bektasevic",
    "telefon":"061459753",
    "jmbg":15299991707,
    "datum_zaposljavanja":"2020-09-21"
}


###
delete  https://nrs-backend.herokuapp.com/people/181
content-Type: application/json

{
}


###
post  https://nrs-backend.herokuapp.com/warehouses/1/items/71
content-Type: application/json

{
    "quantity":33
}

###
get  https://nrs-backend.herokuapp.com/warehouses/1/items
content-Type: application/json

{
}


###
delete  https://nrs-backend.herokuapp.com/warehouses/1/items/71
content-Type: application/json

{
}


###

DELETE https://nrs-backend.herokuapp.com/warehouses/1/items/1
content-Type: application/json

{
    "supplierId": "1"
}
###
POST https://nrs-backend.herokuapp.com/warehouses/31/items/41
content-Type: application/json

{
    "apy_key": "AIzaSyCeJLveAW9reXowkdJCjlDoMf4mNpn5pzc",
    "quantity": "34"
}
###

POST http://localhost:8080/suppliers/1/items/7


###

PUT https://nrs-backend.herokuapp.com/suppliers/11
content-Type: application/json

{
    "apy_key": "AIzaSyCeJLveAW9reXowkdJCjlDoMf4mNpn5pzc",
    "naziv" : "Violeta"
}

###
GET http://localhost:8080/purchases


###

DELETE http://localhost:8080/purchases/2
content-Type: application/json

{
    "supplierId": "1"
}
###
PUT http://localhost:8080/purchases/1
content-Type: application/json

{
    "korisnicki_racun" : "1"
}
###

POST http://localhost:8080/suppliers/1/items/7


###

PUT http://localhost:8080/orders/5/items/7
content-Type: application/json

{
    "supplierId": "1",
    "quantity": "15"
}

###

POST http://localhost:8080/users/login 
content-Type: application/json

{
"name": "Kyle", "password": "password"
}