###
//get all items of purchase with id 1
GET https://nrs-backend.herokuapp.com/purchases/1/items


###

DELETE https://nrs-backend.herokuapp.com/purchases/1/items/7

###

DELETE https://nrs-backend.herokuapp.com/purchases/1/items

###

//quantity is mandatory
PUT https://nrs-backend.herokuapp.com/purchases/1/items/7
content-Type: application/json

{
    "quantity": "5"
}

###
//quantity is mandatory
POST https://nrs-backend.herokuapp.com/purchases/1/items/7
content-Type: application/json

{
    "quantity": "15"
}

###